### ISSUE TITLE
Barterdex for Win 1.3 (latest) Hangs on login

### ISSUE THREAD

**Issue by togethercrypton** [buildog/BarterDEX#53] opened 2017-11-07 14:53 UTC
With the latest version of Barterdex - I installed the latest binaries and attempted to login with generated pass - hung for 20 mins before giving up. 
Clean install - uninstalled old(er) version and now been hanging on login since 8 am (8:52 at time of writing).

Collaborated with two other MNZ community members - 
also had the same issues
OS: windows 10 with latest updates

**Comment by buildog** [comment] 2017-11-07 23:03
duplicate of #49 
it's because of a bug we had with whitespace in the passphrase, will be fixed in next release.
Thanks @togethercrypton

**Closed by buildog** 2017-11-07 23:03 UTC
