### ISSUE TITLE
No user feedback of swap initiation

### ISSUE THREAD

**Issue by n41r0j** [buildog/BarterDEX#8] opened 2017-10-20 18:00 UTC
When an amount for a swap is entered and the button to trade is clicked, the screen goes to a screen saying 'Processing trade order'. After a while, this screen goes back to where the amount to trade was entered. It feels like the swap was unsuccessful, but in the background, the swap was initiated successfully. 
It feels that the swap was unsuccessful, and because the screen returns to the input screen, it is very tempting to click the trade button again, doing a second, probably unwanted, swap.

**Comment by buildog** [comment] 2017-10-20 23:04
maybe dupe of https://github.com/buildog/BarterDEX/issues/7 ?

**Comment by n41r0j** [comment] 2017-10-21 05:54
No, this is when you click the 'Trade' button. BarterDEX will go to 'Processing order' load screen and stays there for a while. After a while, the screen goes away. The user doesn't know whether the trade went through. No 'Trade initiated successfully' message of some kind.

**Comment by jl777** [comment] 2017-10-23 18:59
probably it is good to do a recentswaps call, which returns the status of the pending request, along with how much more time is left before it expires. once it starts, then the requestid/quoteid can be used to query the detailed status of a swap.

once the three transactions are locked, it is mostly a matter of staying online and finishing the protocol. in the even the three transactions (bobdeposit, alicepayment, bobpayment) are not locked, then depending on the specific scenario the swap needs to be unwound, but all this is automatically handled by the swapstatus call

**Comment by buildog** [comment] 2017-11-07 02:55
done via growler and order tab

**Closed by buildog** 2017-11-07 02:55 UTC
Labels: feature, UX
